apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: busybox-http-app
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: busybox-http-app
    labels:
      app: busybox-http-app
  stringData:
    key1: value1
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: busybox-http-app
      deploymentconfig: busybox-http-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        creationTimestamp: null
        labels:
          app: busybox-http-app
          deploymentconfig: busybox-http-app
      spec:
        containers:
        - env:
          - name: key1String
            value: value1String
          - name: key1FromSecret
            valueFrom:
              secretKeyRef:
                key: key1
                name: busybox-http-app
          imagePullPolicy: IfNotPresent
          image: ''
          name: busybox-http-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/data
            name: busybox-http-app-data
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: busybox-http-app-data
          persistentVolumeClaim:
            claimName: busybox-http-app
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - busybox-http-app
        from:
          kind: ImageStreamTag
          name: busybox-http-app:${TAG_NUMBER}
          namespace: busybox
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    host: busybox-http-app-busybox.192.168.42.203.nip.io
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: busybox-http-app
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      app: busybox-http-app
    name: busybox-http-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: busybox-http-app
      deploymentconfig: busybox-http-app
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: busybox-http-app
    labels:
      app: busybox-http-app
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
  - name: TAG_NUMBER
    description: "Tag Number of the docker image"
    value: latest
